---

version: '3.9'

services:
  # https://www.portainer.io/
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    environment:
      - TZ=Europe/Skopje
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/portainer/data:/data

  # https://mosquitto.org/
  mosquitto:
    container_name: mosquitto_broker
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8883:8883"  # MQTT over TLS/SSL port
    environment:
      - TZ=Europe/Skopje
    volumes:
      - /etc/mosquitto/config:/mosquitto/config
      - /etc/mosquitto/data:/mosquitto/data
      - /etc/mosquitto/log:/mosquitto/log
