---

- hosts: LOCAL_LAN_BROKERS
  become: true
  gather_facts: true
  
  ###### Variables ######
  vars:
    allowed_ssh_networks:
      - <ROUTER_NETWORK_IP_ADDRESS>
      - 10.10.10.0/24
    unnecessary_services: null
    unnecessary_software:
      - tcpdump
      - nmap-ncat
      - wpa_supplicant
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
      vm.mmap_rnd_bits: 18
    ssh_custom_options:
      - Include /etc/ssh/ssh_config.d/*
    sshd_custom_options:
      - AcceptEnv LANG

  #### Collections ####
  collections:
    - devsec.hardening

  #### Roles ####
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening

  ###### Tasks ######
  tasks:
    - name: Add SSH port to internal zone
      ansible.posix.firewalld:
        zone: internal
        service: ssh
        state: enabled
        immediate: true
        permanent: true

    - name: permit traffic in default zone for https service
      ansible.posix.firewalld:
        zone: internal
        service: https
        permanent: true
        immediate: true
        state: enabled

    - name: permit traffic in default zone for https service
      ansible.posix.firewalld:
        zone: internal
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Add permitted networks to internal zone
      ansible.posix.firewalld:
        zone: internal
        source: '{{ item }}'
        state: enabled
        immediate: true
        permanent: true
      with_items: '{{ allowed_ssh_networks }}'

    - name: Drop ssh from the public zone
      ansible.posix.firewalld:
        zone: public
        service: ssh
        state: disabled
        immediate: true
        permanent: true

    - name: Remove undesirable packages
      package:
        name: '{{ unnecessary_software }}'
        state: absent

    - name: Stop and disable unnecessary services
      service:
        name: '{{ item }}'
        state: stopped
        enabled: false
      with_items: '{{ unnecessary_services }}'
      ignore_errors: true

    - name: Set a message of the day
      copy:
        dest: /etc/motd
        src: ../files/etc/motd
        owner: root
        group: root
        mode: 420

    - name: Set a login banner
      copy:
        dest: '{{ item }}'
        src: ../files/etc/issue
        owner: root
        group: root
        mode: 420
      with_items:
        - /etc/issue
        - /etc/issue.net
