---
- hosts: LOCAL_LAN_BROKERS
  become: true
  gather_facts: true

  ###### Variables ######

  ###### Tasks ######
  tasks:
    - name: Install docker
      ansible.builtin.shell: curl -sSL https://get.docker.com | sh

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        append: true
        groups: docker

    - name: Enable Docker IPv6
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        mode: 0600
        content: |
          {
            "ipv6": true,
            "fixed-cidr-v6": "2001:db8:1::/64"
          }
      notify: Restart Docker

    - name: Install docker-compose, pyyaml
      ansible.builtin.shell: pip3 -v install docker-compose pyyaml
      args:
        creates: /usr/local/bin/docker-compose

    - name: Install tailscale
      ansible.builtin.shell: curl -fsSL https://tailscale.com/install.sh | sh

  ###### Handlers ######
  handlers:
    - name: Restart Docker
      ansible.builtin.shell:
        name: docker
        state: restarted
